# NOTE: update this with your service name
service: square-squash-db

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  environment: ${file(env.yml):${self:provider.stage}}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 256
  timeout: 1
  # TODO: double check this....
  # https://github.com/mugglmenzel/serverless-examples-cached-rds-ws/blob/master/serverless.yml
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - ec2:CreateNetworkInterface
      - ec2:DescribeNetworkInterfaces
      - ec2:DeleteNetworkInterface
    Resource: "*"
  # Connection to DB params - env variable to all functions
  environment:
    HOST: { "Fn::GetAtt" : ["ScoresTable", "Endpoint.Address" ]}
    PORT: {"Fn::GetAtt" : ["ScoresTable", "Endpoint.Port" ]}
    USER: ${self:custom.environment.DB_USER}
    PASSWORD: ${self:custom.environment.DB_PASS}
  #Mega bleh
  vpc:
    securityGroupIds:
      - sg-51b8021e
    subnetIds:
      - subnet-62c84805
      - subnet-922d579d
      - subnet-b8fd70e4
      - subnet-a3c2169d
      - subnet-b22b7bf8
      - subnet-d7d35cf9


functions:
  UpdateUser:
    handler: API/UpdateUser.updateUser
    events:
      - http:
          path: score
          method: post
  GetTopScores:
    handler: API/GetTopScores.getTopScores
    events:
      - http:
          path: score
          method: get
  MakeDb:
    handler: API/MakeDb.makeDb

resources:
  Resources:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html
    # https://serverless-stack.com/chapters/configure-dynamodb-in-serverless.html
    ScoresTable:
      Type: AWS::RDS::DBInstance
      Properties: 
        DBName: SquareSquashDB
        DBInstanceClass: db.t2.micro
        DBInstanceIdentifier: SquareSquashDBS
        Engine: MySQL
        EngineVersion: "5.6.40"
        MasterUsername: ${self:custom.environment.DB_USER}
        MasterUserPassword: ${self:custom.environment.DB_PASS}
        DeletionProtection: false
        AllocatedStorage: "20"
  Outputs:
    MyDbEndpoint:
      Description: The Endpoint for the MYSQL server.
      Value: { "Fn::GetAtt" : ["ScoresTable", "Endpoint.Address" ]}
    MyDbPort:
      Description: The Port for the MYSQL server.
      Value: { "Fn::GetAtt" : ["ScoresTable", "Endpoint.Port" ]}